name: AzionCli

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    name: AzionCli
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Run test script
        run: |
          bash ./tests/azion_cli/test.sh
