name: AzionCli

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    name: AzionCli
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Run test script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          WEBHOOK_SLACK_URL: ${{ secrets.WEBHOOK_SLACK_URL }}
        run: |
          bash ./tests/azion_cli/test.sh
