name: Gen JSOC and Update Function

on:
  push:
    branches:
      - main
env:
  HUSKY: 0

jobs:
  publish-jsdoc:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.18
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SO deps
        run: apk add curl git bash jq

      - name: Install dependencies
        run: npm install

      - name: Install current library globally
        run: npm install -g

      - name: Run task:docsx
        run: npm run task:docs

      - name: List files
        run: ls

      - name: Change directory and build
        run: |
          cd jsdoc/edge-functions/$(jq -r ".version" package.json)
          vulcan build --preset html --mode deliver

      - name: Authenticate and deploy
        run: |
          cd jsdoc/edge-functions/$(jq -r ".version" package.json)
          DEBUG=true vulcan auth --token ${{ secrets.RTM_TOKEN }}
          DEBUG=true vulcan deploy --functionID ${{ secrets.VULCAN_DOCS_EDGE_FUNCTION_ID }}
