name: Gen JSOC and Update Function

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage
env:
  HUSKY: 0

jobs:
  publish-jsdoc:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.18
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SO deps
        run: apk add curl git bash jq

      - name: Install dependencies
        run: npm install

      - name: Install current library globally
        run: npm install -g

      - name: Run task:docsx
        run: npm run task:docs

      - name: List files
        run: ls

      - name: Copy azion directory
        run: |
          cp -r ./azion jsdoc/edge-functions/$(jq -r ".version" package.json)

      - name: Change directory
        run: cd jsdoc/edge-functions/$(jq -r ".version" package.json)

      - name: Create args file
        run: |
          cat > ./args.json << EOF
            { "my_arg_by_action": true }
          EOF

      - name: Change directory for edge-computing-deploy
        run: cd jsdoc/edge-functions/$(jq -r ".version" package.json)

      - name: List files
        run: ls

      - name: edge-computing-deploy
        id: azion_edge
        uses: aziontech/edge-computing-actions@v0
        with:
          azionPersonalToken: ${{ secrets.RTM_TOKEN }}
          functionArgsFilePath: './args.json'
          buildPreset: 'html'
          buildMode: 'deliver'

      - name: Get the output Azion Edge Deploy
        run: |
          echo "Application ID-= ${{ steps.azion_edge.outputs.applicationId }}"
          echo "Domain-= ${{ steps.azion_edge.outputs.domainUrl }}"
